name: Build and Push Docker Images

on:
  push:
    branches: [ "qa" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest

  deploy-aws:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
        chmod 600 key.pem

    # Update and configure the first instance
    - name: Update system and install Docker (Instance 1)
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_1 }} << 'EOF'
        sudo yum update -y
        if ! command -v docker &> /dev/null
        then
          echo "Docker not found, installing..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        else
          echo "Docker is already installed."
        fi
        sudo systemctl start docker
        sudo systemctl enable docker
        EOF

    - name: Deploy Docker Container (Instance 1)
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} << 'EOF'
        sudo docker stop my-html-app || true
        sudo docker rm my-html-app || true
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest
        sudo docker run -d -p 8080:80 --name my-html-app ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest
        EOF

    # Update and configure the second instance
    - name: Update system and install Docker (Instance 2)
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA2 }} << 'EOF'
        sudo yum update -y
        if ! command -v docker &> /dev/null
        then
          echo "Docker not found, installing..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        else
          echo "Docker is already installed."
        fi
        sudo systemctl start docker
        sudo systemctl enable docker
        EOF

    - name: Deploy Docker Container (Instance 2)
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_2 }} << 'EOF'
        sudo docker stop my-html-app || true
        sudo docker rm my-html-app || true
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest
        sudo docker run -d -p 8080:80 --name my-html-app ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest
        EOF
